spring.application.name=pisip
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/pisip
spring.datasource.username=postgres
spring.datasource.password=Pilsener.2020
spring.jpa.show-sql=true